[book]
src = "src"
title = ""

[output.html]
additional-css = ["book.css"]
additional-js = ["solidity.min.js"]
git-repository-url = "https://github.com/ava-labs/teleporter"
no-section-label = true

[output.html.fold]
enable = true
