name: ABI Go Binding

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.7"

jobs:
  abi_binding:
    name: abi_binding
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout go-ethereum repository
        uses: actions/checkout@v4
        with:
          repository: ethereum/go-ethereum
          ref: v1.13.1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install abigen tool
        run: |
          make
          make devtools

      - name: Checkout Teleporter repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check ABI Go bindings
        run: |
          ./scripts/abi_go_bindings.sh
          .github/workflows/check_clean_branch.sh
