name: ABI Go Bindings Checker

on:
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.8"

jobs:
  abi_binding:
    name: abi_binding
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Teleporter repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install forge and generate ABI Go bindings
        run: |
          BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          $BASE_DIR/.foundry/bin/foundryup
          export GOPATH=$HOME/go
          export PATH="$PATH:$BASE_DIR/.foundry/bin"
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/abi_go_bindings.sh

      - name: Check for clean branch
        run: .github/workflows/check_clean_branch.sh
