name: Forge docs checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.8"

jobs:
  docs_checker:
    name: docs_checker
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Teleporter repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate forge docs
        run: |
          cd contracts
          forge docs --build

      - name: Print diff
        run: git --no-pager diff -- contracts/docs/

      - name: Fail if diff exists
        run: git --no-pager diff --quiet -- contracts/docs/