# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  e2e_tests:
    name: e2e_tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Go version
        run: |
          source ./scripts/versions.sh
          GO_VERSION=$GO_VERSION >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Run E2E Tests
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/local/e2e_test.sh
