name: go.mod Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  gomod_check:
    name: Check go.mod
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: GO_VERSION=$(sed -En 's/^go (.*)$/\1/p' go.mod).$(sed -En 's/\/\/ GO_PATCH_VERSION (.*)$/\1/p' go.mod) >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go mod tidy
      - run: git --no-pager diff -- go.mod go.sum
      - run: git --no-pager diff --quiet -- go.mod go.sum