name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  solhint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout teleporter
      uses: actions/checkout@v4

    - name: Install solhint
      run: |
        npm install solhint -g
        solhint --version

    - name: Run Lint
      run: |
        ./scripts/lint.sh -l sol

  golangci:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repositories and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set Go version
      run: |
        source ./scripts/versions.sh
        GO_VERSION=$GO_VERSION >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run Lint
      run: |
        ./scripts/lint.sh -l go
