name: slither Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  slither-analyze:
    name: Slither Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Slither
        uses: crytic/slither-action@6ef3a33e56de4e8f59488cf60858b5c1bf4967c0
        id: slither
        continue-on-error: true
        with:
          target: "contracts/"
          sarif: results.sarif
          slither-config: "contracts/slither.config.json"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
